### ISSUE TITLE
imageVersionnotusinglatest and AC_DOCKER_0041 Issue

### ISSUE THREAD

**Issue by ZNozomi** [tenable/terrascan#1099]
The description for imageVersionnotusinglatest in AC_DOCKER_0041 is incorrect
The description is "Ensure platform flag with FROM command is not used for Docker file"
This is the exact same description as the one for docFilePlatformFlag in AC_DOCKER_0001

AC_DOCKER_0041, and thus imageVersionnotusinglatest, is not in the Docker Policies documentation
https://runterrascan.io/docs/policies/docker/

imageVersionnotusinglatest does not seem to work as intended
It should make a finding if the latest tag is used or if there is no tag
However, there are findings for "FROM python:alpine" and "FROM python:3.9"
Changing ":v" to ":" in line 12 of imageVersionnotusinglatest.rego fixes the issue

imageVersionnotusinglatest should be renamed to something like imageVersionUsingLatest to be consistent with other policies
Ex 1, runUsingApt makes a finding if apt is used with RUN 
Ex 2, docFilePlatformFlag makes a finding if platform flag is used with FROM

**Comment by nasir-rabbani** [comment]
closed by #1523
