### ISSUE TITLE
accurics.gcp.IAM.145 triggers for GitHub repos

### ISSUE THREAD

**Issue by jkamenik** [tenable/terrascan#1295]
* terrascan version: 1.15.2
* Operating System: docker

### Description

`accurics.gcp.IAM.145` is incorrectly implemented as a copy-paste of `accurics.github.IAM.1`

### What I Did

```terraform
resource "github_repository" "test-repo" {
  name       = "my-test-repo"
  visibility = "public"
}
```

Fires `accurics.github.IAM.1` and `accurics.gcp.IAM.145` but should only fire `accurics.github.IAM.1`.  

Incorrect code is: https://github.com/tenable/terrascan/blob/v1.15.2/pkg/policies/opa/rego/gcp/github_repository/privateRepoEnabled.rego

Probably should be updated to check GCP git repository, or be removed entirely.

**Comment by ejether** [comment]
I've also run into this issue. I'm glad to see a fix is coming. 🥳
