### ISSUE TITLE
resource ID has an invalid format Dockerfile

### ISSUE THREAD

**Issue by nhalstead** [tenable/terrascan#1344]
* terrascan version: v1.15.2 (via Docker Image Tag Latest)
* Operating System: Docker Container

### Description

```
{"level":"error","time":"2022-07-27T22:40:57.851Z","file":"opa/engine.go:419","msg":"resource ID has an invalid format Dockerfile"}
```

[opa/engine.go:419](https://github.com/tenable/terrascan/blob/master/pkg/policy/opa/engine.go#L419)

### What I Did

- Checked issues in terrascan repo (none)
- Checked Dockerfiles, all are correct format

Is it possible to have a Flag to skip errors during the engine's `FindAllResourcesByID` error check?

**Comment by gaurav-gogia** [comment]
Hi @nhalstead 

Could you please share a sample docker file code where you see these errors?

Thanks

**Comment by nhalstead** [comment]
Hi @gaurav-gogia I was able to bypass the exit code error BUT the output JSON is messed up with error values when it should come out on Standard Error, not Standard Output.

#### Command:

```bash
terrascan scan --output json --log-type console --use-colors false > report.json 2> error.txt || true
```

#### error.txt

```
Unable to find image 'tenable/terrascan:latest' locally
latest: Pulling from tenable/terrascan
2408cc74d12b: Already exists
...
6eb609282c41: Pull complete
Digest: sha256:e36aed65df132ffb722b6b524f703eb819cbf17efb7ba5a9397a4b908e87e30e
Status: Downloaded newer image for tenable/terrascan:latest
2022-08-29T20:56:55.100Z	[31merror[0m	opa/engine.go:419	resource ID has an invalid format Dockerfile
```

#### report.json:

```json
ERROR: json: cannot unmarshal number into Go struct field Function_Environment.Properties.Environment.Variables of type string
{
  "results": {
    "scan_errors": [
      {
...
```

**Comment by gaurav-gogia** [comment]
@nhalstead 

I see. That might be a separate issue. Might require some design changes around how errors are being handled. Currently all logs are written to Standard Output, AFAIK. 

Could you please open a separate issue for this?

**Comment by gaurav-gogia** [comment]
Closed in favour of [1378](https://github.com/tenable/terrascan/issues/1378)

**Comment by nhalstead** [comment]
Hi @gaurav-gogia are you able to get a release of the changes?
