### ISSUE TITLE
Docs don't mention pre-requirements

### ISSUE THREAD

**Issue by VeraBE** [tenable/terrascan#1345]
The [contribution guidelines](https://github.com/tenable/terrascan/blob/master/CONTRIBUTING.md) and [README](https://github.com/tenable/terrascan#building-terrascan) don't mention that gcc and Go are pre-requirements. Is there a specific Go version we should use?

**Comment by gaurav-gogia** [comment]
Hi @VeraBE 

You should be good as long as you use Go v1.17 or above

As for missing information in docs. Would you like to take this issue and send a PR?
