### ISSUE TITLE
Calling attention to your documentation...

### ISSUE THREAD

**Issue by tspearconquest** [tenable/terrascan#1384]
Hello,

I'm simply filing this issue in order to get the developers attention regarding a pull request and open issue over in the https://github.com/tenable/runterrascan.io project.

**Comment by tspearconquest** [comment]
Pull request: https://github.com/tenable/runterrascan.io/pull/59
Related to issue: https://github.com/tenable/runterrascan.io/issues/70

**Comment by gaurav-gogia** [comment]
Hi @tspearconquest 

Thanks for bringing this to our attention. I've reviewed the PR.
